%hijo
hijo(guillermoIV,jorgeIII).
hijo(victoria,guillermoIV).
hijo(eduardoVII,victoria).
hijo(jorgeV,eduardoVII).
hijo(jorgeVI,jorgeV).
hijo(eduardoVIII,jorgeV).
hijo(isabelII,jorgeVI).
hijo(margarita,jorgeVI).
hijo(carlos,isabelII).
hijo(anna,isabelII).
hijo(andres,isabelII).
hijo(guillermo,carlos).
hijo(harry,carlos).
hijo(jorge,guillermo).
hijo(carlota,guillermo).
hijo(luis,guillermo).
hijo(archie,harry).
%padre
padre(X,Y):-hijo(Y,X).
%abuelo
abuelo(X,Y):-hijo(Z,X),hijo(Y,Z).
%hermano
hermano(X,Y):-hijo(X,Z),hijo(Y,Z),not(X=Y).
%tio
tio(X,Y):-hermano(Z,X),hijo(Y,Z).
%sobrino
sobrino(X,Y):-tio(Y,X).
%primo
primo(X,Y):-hijo(Y,Z),sobrino(X,Z).
%bisabuelo
bisabuelo(X,Y):-hijo(Z,X),abuelo(Z,Y).
%tatarabuelo
tatarabuelo(X,Y):-bisabuelo(Z,Y),hijo(Z,X).
%nieto
nieto(X,Y):-abuelo(Y,X).
%bisnieto
bisnieto(X,Y):-bisabuelo(Y,X).
%tataranieto
tataranieto(X,Y):-tatarabuelo(Y,X).
%ancestro
ancestro(X,Y):-padre(X,Y).
ancestro(X,Y) :- padre(X,Z),ancestro(Z,Y).
